// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Android-only configuration for the Zaxo app.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  ///
  /// Since Zaxo is Android-only, this always returns Android options.
  static FirebaseOptions get currentPlatform => android;

  /// Firebase options for the Android platform.
  ///
  /// Project: zaxoeucc
  /// Database URL: https://zaxoeucc-default-rtdb.firebaseio.com
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmanQkwIbwwBeL34J2vy6eEB3VkOq2YM',
    appId: '1:607239970175:android:8f30b284e3f2c490bbce4a',
    messagingSenderId: '607239970175',
    projectId: 'zaxoeucc',
    databaseURL: 'https://zaxoeucc-default-rtdb.firebaseio.com',
    storageBucket: 'zaxoeucc.firebasestorage.app',
  );

  /// Auth domain for the Firebase project.
  static const String authDomain = 'zaxoeucc.firebaseapp.com';

  /// Measurement ID for Google Analytics.
  static const String measurementId = 'G-XJQHLKSM6G';
}
